#!/bin/bash

SBT=sbt

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Export the keystore password for use in ws.conf
export KEY_PASSWORD=`cat scripts/password`

JVM_OPTIONS="$JVM_OPTIONS -Dkey.password=$KEY_PASSWORD"
JVM_OPTIONS="$JVM_OPTIONS -DcertificateDirectory=$DIR/scripts"

AGENT=$DIR/target/universal/stage/jetty-alpn-agent/jetty-alpn-agent-2.0.6.jar


# Run Play (this should work for both run and start).
SBT_OPTS=-javaagent:$AGENT $SBT $JVM_OPTIONS "$* $JVM_OPTIONS";
