#!/bin/bash

set -x

# Export the keystore password for use in ws.conf
export KEY_PASSWORD=$(<scripts/password)

AGENT=$(find ~/.ivy2/cache -name 'jetty-alpn-agent-*.jar' | head -1)
if [ -n "$AGENT" ]; then
    SBT_OPTS+=" -javaagent:$AGENT"
    export SBT_OPTS
fi
sbt "$@"
